@extends('common::framework')

{{--
    Keekii typography pairing.

    Body/UI resolves to var(--be-font-family, var(--font-sans)) in common.css.
    Nothing in this repo imports @fontsource-variable/inter, so Inter is not
    applied from the stylesheet; if the database theme row sets a font_family
    the vendor layout links it from Google Fonts instead.

    Bricolage Grotesque is the display face, reserved for brand moments and
    applied via the `keekii-display` utility in resources/client/keekii-brand.css,
    where the @font-face now lives.

    It was previously pulled from fonts.googleapis.com. That cost a
    render-blocking stylesheet plus DNS and TLS to two third-party origins
    before any heading could paint, and added a third-party origin to the
    critical path of the most visible text on the page. It is now self-hosted
    from /fonts, which is why this section preloads a font file instead of
    linking a stylesheet.

    The preload needs `crossorigin` even though the request is same-origin:
    font fetches are always made in CORS mode, and without the attribute the
    browser would download the file twice -- once for the preload and again for
    the @font-face. `type` is declared so a browser that does not support
    woff2 skips the fetch instead of downloading a file it cannot parse.
--}}
@section('head-end')
    {{--
        PWA installability.

        These were all missing, so the app was not installable: a service worker
        was registered and both the Vite PWA config and resources/client/sw.ts
        precached /manifest.json, but no such file was ever served. The worker
        was precaching a 404.

        Icons are generated by scripts/generate-pwa-icons.ps1 and must not be
        hand-edited -- that script fails if the artwork stops separating from its
        plate.

        The tab favicon is the one surface where the artwork *is* the whole
        background, so it is the one place the light and dark variants genuinely
        differ: a light plate on a dark tab reads as a bright square. Both SVGs
        are offered and the browser picks, via prefers-color-scheme. The PNG
        fallbacks below are unconditioned and therefore always the light plate,
        which is the safer of the two at 16px.

        The 32 and 16 PNGs exist for browsers that do not support SVG favicons.
        apple-touch-icon is required or iOS shows a screenshot of the page; it
        cannot be conditioned, so it is the light plate.

        `theme-color` is the brand orange used as text and controls, which is
        #d84b00 in the theme but resolves to roughly #ce4804 once rounded into
        the OKLCH token. It is a fixed value because a static meta tag cannot
        follow the light/dark theme; this is the light-theme accent.
    --}}
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" media="(prefers-color-scheme: light)">
    <link rel="icon" type="image/svg+xml" href="/favicon-dark.svg" media="(prefers-color-scheme: dark)">
    <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon-16.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png">

    <meta name="theme-color" content="#d84b00">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="Keekii">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <link rel="preload" as="font" type="font/woff2"
        href="/fonts/bricolage-grotesque-latin-variable.woff2" crossorigin>
@endsection

@section('angular-styles')
    {{--angular styles begin--}}
		<link rel="stylesheet" href="client/styles.41f9cd8f18e85618bcff.css" media="print" onload="this.media=&apos;all&apos;">
		<link rel="stylesheet" href="client/styles.41f9cd8f18e85618bcff.css">
	{{--angular styles end--}}
@endsection

@section('angular-scripts')
    {{--angular scripts begin--}}
		<script>setTimeout(function() {
        var spinner = document.querySelector('.global-spinner');
        if (spinner) spinner.style.display = 'flex';
    }, 100);</script>
		<script src="client/runtime-es2015.4ec88a97768e8a190cb3.js" type="module"></script>
		<script src="client/runtime-es5.4ec88a97768e8a190cb3.js" nomodule defer></script>
		<script src="client/polyfills-es5.7dec1fefa52cfcc5108b.js" nomodule defer></script>
		<script src="client/polyfills-es2015.f93fa6be99734e20273f.js" type="module"></script>
		<script src="client/main-es2015.d89b74fa071930a4d73f.js" type="module"></script>
		<script src="client/main-es5.d89b74fa071930a4d73f.js" nomodule defer></script>
	{{--angular scripts end--}}
@endsection
