<?php

return [
    'positions' => array_filter([
        [
            'name' => 'sidebar-primary',
            'label' => 'Sidebar primary',
            'route' => '/',
        ],
        [
            'name' => 'sidebar-secondary',
            'label' => 'Sidebar secondary',
            'route' => '/',
        ],
        [
            'name' => 'mobile-bottom',
            'label' => 'Mobile bottom',
            'route' => '/',
        ],
        [
            'name' => 'landing-page-navbar',
            'label' => 'Landing page navbar',
            'route' => '/?forceHomepage=landing',
        ],
    ]),
    'available_routes' => [
        '/upload',
        '/search',
        '/library',
        '/library/songs',
        '/library/albums',
        '/library/artists',
        '/library/downloads',
        '/library/history',
        '/admin/upload',
        '/admin/channels',
        '/admin/artists',
        '/admin/albums',
        '/admin/tracks',
        '/admin/genres',
        '/admin/lyrics',
        '/admin/playlists',
        '/admin/backstage-requests',
        '/admin/comments',
        '/backstage/requests',
        // Public company, plans and legal pages. These are React routes rather
        // than admin destinations, but the menu editor can only offer a path
        // that appears here, so without this list the new pages cannot be
        // linked from any DB-driven menu. Keep in sync with the canonical
        // source of truth in resources/client/company/company-site-map.ts.
        '/about',
        '/advertising',
        '/artists',
        '/authors',
        '/communities',
        '/creators',
        '/developers',
        '/for-the-record',
        '/investors',
        '/jobs',
        '/vendors',
        '/free-mobile-app',
        '/import-your-music',
        '/popular-by-country',
        '/support',
        '/top-song-lyrics',
        '/plans',
        '/plans/keekii-free',
        '/plans/premium-duo',
        '/plans/premium-family',
        '/plans/premium-individual',
        '/plans/premium-student',
        '/legal',
        '/privacy-policy',
        '/cookies',
        '/about-ads',
        '/accessibility',
        '/gdpr',
    ],
];
